### ISSUE TITLE
Request has failed; please try later

### ISSUE THREAD

**Issue by pstaven** [Wildric-Auric/MidJourney-Wrapper#19]
Hi,

I think I've install wrapper correctly but still I am not able to generate pictures.
It just keeps saying "Request has failed; please try later"

Here is my sample:

#every variable is a string

DAVINCI_TOKEN = "My servers bot token that I've created"

SERVER_ID = [My server id]

CHANNEL_ID = [My channel id - can there be multiple?]

SALAI_TOKEN = "my account token that I've paid"

MID_JOURNEY_ID = "936929561302675456"  #midjourney bot id
#don't edit the following variable
targetID       = ""
targetHash     = ""

Do I need to add some info to "targetID and targetHash" part? and if yes - what do I need to add there?

Sorry for stupid questions

**Comment by batuhansevinc** [comment]
You need to give a role to your bot. I think your bot can not access to your private channels.

**Comment by pstaven** [comment]
Thanks. I added roles to server&channel but I still have the same issue

**Comment by Wildric-Auric** [comment]
In you console you should see an error when you get "Request failed"

**Comment by pstaven** [comment]
It gave me this:

Ignoring exception in command mj_imagine:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/commands/core.py", line 982, in _invoke
    await self.callback(ctx, **kwargs)
  File "/Users/petteristaven/Documents/bots/MidJourney-Wrapper-main/main.py", line 23, in mj_imagine
    await ctx.respond("Request has failed; please try later")
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/commands/context.py", line 282, in respond
    return await self.interaction.response.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/interactions.py", line 825, in send_message
    await self._locked_response(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/interactions.py", line 1090, in _locked_response
    await coro
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction

**Comment by Wildric-Auric** [comment]
Just to be sure, SERVER_ID and other variables aren't in a list? They are just string.
Secondly, I think you have all commands that don't work like */hello*, is that true? If the answer is yes, the problem is from the bot/it's connection, and not the request made by Salai, and then because It's pycord that handles all that you may try updating it.

**Comment by pstaven** [comment]
Yes all the ID and token are here as string

DAVINCI_TOKEN = "xxx"

SERVER_ID = "xxx"

CHANNEL_ID = "xxx"

SALAI_TOKEN = "xxx"

MID_JOURNEY_ID = "936929561302675456"  #midjourney bot id
#don't edit the following variable
targetID       = "" <-- Do I need to fill here some info?
targetHash     = ""  <-- Do I need to fill here some info?

Commands work. /Hello works just fine. I am not just able to generate image. it says "Request has failed; please try later"

**Comment by Wildric-Auric** [comment]
ok I see
In main.py, just after the line where there is `reponse=...` (see image) try adding `print(response)` so that we can get more info about the error
<img width="396" alt="image" src="https://user-images.githubusercontent.com/70033490/218698884-40fa162c-a1ec-4e63-9656-a04863c42bc6.png">
*(You don't need to fill target variables by the way)*

**Comment by pstaven** [comment]
It works now.
I didn't have the original midjourney bot at the server anymore..

Sorry for trouble and thanks for the help!

**Comment by Wildric-Auric** [comment]
This makes me think of making error handling system that can tell more about potential origin of errors. Glad your problem is solved.
