### ISSUE TITLE
python3 main.py Logged in as DAVINCI#0703

### ISSUE THREAD

**Issue by ondraasek** [Wildric-Auric/MidJourney-Wrapper#23]
Hi,
it says:

$ python3 main.py
Logged in as DAVINCI#0703

but it doesnt work on the discord server, I Dont see any bot and commands doesnt work, do you have an idea why? thanks a lot

**Comment by ondraasek** [comment]
I needed to add discord token like this:

DAVINCI_TOKEN = "TOKEN"
wihout ""
I got: 

Traceback (most recent call last):
  File "/home/deeply/midjourney/main.py", line 2, in <module>
    import Globals
  File "/home/deeply/midjourney/Globals.py", line 3
    DAVINCI_TOKEN = dasdasdasMTgyMDM1OTcxMQ.Gr98Fe.7gpsdadadsasadsaoGCXU
                                                      ^
SyntaxError: invalid decimal literal

**Comment by ondraasek** [comment]
I just dont see that bot on my channel or if I do /mj its doing nothing, but its logged in

**Comment by ondraasek** [comment]
Forgot to invite bot, but now I am getting this:

    await self.register_commands()
  File "/home/deeply/.local/lib/python3.10/site-packages/discord/bot.py", line 460, in register_commands
    await self.http.bulk_upsert_command_permissions(
  File "/home/deeply/.local/lib/python3.10/site-packages/discord/http.py", line 338, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed
Logged in as DAVINCI#0703


if I do /hello at discord, it works, but davinci
/mj says:
DAVINCI
BOT
 — Today at 6:55 PM
Request has failed; please try later

**Comment by ondraasek** [comment]
I think I have bad midjourney key, have no idea where to get it
https://www.midjourney.com/account/keys/
found something here or at card here https://www.midjourney.com/pass/
have no idea what to put to SAIL thanks a lot for advise
