### ISSUE TITLE
Couldn't run this code

### ISSUE THREAD

**Issue by MikeJackOne** [Wildric-Auric/MidJourney-Wrapper#44]
Hi I install all the required library,but when I run python main.py I got following error, I created a virtualenv to run this piece of code and I am using Python 3.11.1

`Traceback (most recent call last):
  File "C:\projectx\MidJourney-Wrapper\main.py", line 18, in <module>
    @bot.command(description="This command is a wrapper of MidJourneyAI")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projectx\MidJourney-Wrapper\myenv\Lib\site-packages\discord\bot.py", line 587, in decorator
    result = command(**kwargs)(func)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projectx\MidJourney-Wrapper\myenv\Lib\site-packages\discord\commands\core.py", line 1433, in decorator
    return cls(func, **attrs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\projectx\MidJourney-Wrapper\myenv\Lib\site-packages\discord\commands\core.py", line 555, in __init__
    super().__init__(func, **kwargs)
  File "C:\projectx\MidJourney-Wrapper\myenv\Lib\site-packages\discord\commands\core.py", line 141, in __init__
    from ..ext.commands.cooldowns import CooldownMapping, BucketType, MaxConcurrency
  File "C:\projectx\MidJourney-Wrapper\myenv\Lib\site-packages\discord\ext\commands\__init__.py", line 19, in <module>
    from .flags import *
  File "C:\projectx\MidJourney-Wrapper\myenv\Lib\site-packages\discord\ext\commands\flags.py", line 73, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Program Files\Python311\Lib\dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Program Files\Python311\Lib\dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory`

**Comment by ebullienc3** [comment]
Same here

**Comment by MikeJackOne** [comment]
> Same here

I have rewrite some of these code to fix this

**Comment by leostrong8** [comment]
> can u tell us what u have rewrite?

**Comment by Im-Sue** [comment]
> > 同样在这里
> 
> 我重写了其中一些代码来解决这个问题

I have also encountered this issue and still cannot run. What needs to be addressed

**Comment by MikeJackOne** [comment]
> > > 同样在这里
> > 
> > 
> > 我重写了其中一些代码来解决这个问题
> 
> I have also encountered this issue and still cannot run. What needs to be addressed

Contact me through the email and i will tell you how to do this
