### ISSUE TITLE
DAVINCI_TOKEN is not defined

### ISSUE THREAD

**Issue by cjw-666** [Wildric-Auric/MidJourney-Wrapper#68]
Traceback (most recent call last):
  File "/www/wwwroot/midjourney-wrapper.xstech.technology/main.py", line 2, in <module>
    import Globals
  File "/www/wwwroot/midjourney-wrapper.xstech.technology/Globals.py", line 3, in <module>
    DAVINCI_TOKEN = [MTEwMjY2ODkzOTc1NjA1NjcxNw.GPyQ5B.E-Hv0zpwxxxxxNM]
NameError: name 'MTEwMjY2ODkzOTc1NjA1NjcxNw' is not defined

**Comment by nihs269** [comment]
It should be string bro
DAVINCI_TOKEN = 'MTEwMjY2ODkzOTc1NjA1NjcxNw.GPyQ5B.E-Hv0zpwxxxxxNM'
