### ISSUE TITLE
Still work there?

### ISSUE THREAD

**Issue by kuyin** [Wildric-Auric/MidJourney-Wrapper#7]
I got "Request has failed; please try later" for every command right now.
Still working there?

**Comment by Wildric-Auric** [comment]
I've just tested all commands and they work I don't know why then. Try debugging it

**Comment by kuyin** [comment]
Please help. I got this error:

Ignoring exception in on_connect
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/discord/bot.py", line 793, in on_connect
    await self.register_commands()
  File "/usr/local/lib/python3.9/dist-packages/discord/bot.py", line 460, in register_commands
    await self.http.bulk_upsert_command_permissions(
  File "/usr/local/lib/python3.9/dist-packages/discord/http.py", line 338, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 405 Method Not Allowed (error code: 0): 405: Method Not Allowed

Logged in as Mid_bot#2619

Ignoring exception in command <discord.commands.SlashCommand name=mj_imagine>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/commands/core.py", line 110, in wrapped
    ret = await coro(arg)
  File "/usr/local/lib/python3.9/dist-packages/discord/commands/core.py", line 766, in _invoke
    await self.callback(ctx, **kwargs)
  File "/root/Wrapper/main.py", line 23, in mj_imagine
    await ctx.respond("Request has failed; please try later")
  File "/usr/local/lib/python3.9/dist-packages/discord/interactions.py", line 614, in send_message
    await adapter.create_interaction_response(
  File "/usr/local/lib/python3.9/dist-packages/discord/webhook/async_.py", line 194, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/bot.py", line 520, in process_application_commands
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/discord/commands/core.py", line 306, in invoke
    await injected(ctx)
  File "/usr/local/lib/python3.9/dist-packages/discord/commands/core.py", line 116, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.

**Comment by Wildric-Auric** [comment]
I see. Actually, you should not get an error related to discord package.  Do you have py-cord==2.0.0b1 module?

**Comment by kuyin** [comment]
yeah I do have it
![image](https://user-images.githubusercontent.com/7321275/201521294-a451930e-57cf-4927-8c6c-38b1796bef3e.png)

**Comment by Wildric-Auric** [comment]
I see, that's weird. You have got 40060 as error code which should be related to discord bot; for instance you get it when you forget an await in front of a channel.send(). But you can see that the execution of code passes through the printing of "request failed" which means that there is a problem in PassToSelfBot which reponse status code isn't good, try printing the reponse.text and response.status_code so that we get more info about the error.
I tried on another computer (in windows os) to see if I can reproduce the error but infortunately it works for me.

**Comment by kuyin** [comment]
400
{"message": "Unknown Guild", "code": 10004}

lol wtf

**Comment by Wildric-Auric** [comment]
You had a mistake in the server ID?

**Comment by kuyin** [comment]
Yeah you use your IDs no the parameters xD

**Comment by Wildric-Auric** [comment]
yeah ok, enjoy
