### ISSUE TITLE
bot is not working for me anymore

### ISSUE THREAD

**Issue by torealise** [Wildric-Auric/MidJourney-Wrapper#79]
It was working few weeks ago but today i started it and it is not working. Is it a problem on my side or everyone got it?

**Comment by nihs269** [comment]
Can you be more specific?

**Comment by tizzle** [comment]
Same here,

i found that the MidJourney token had changed (i'm on a monthly subscription), but i still get an error, while the bot now proxies properly:

```
Ignoring exception in command mj_imagine:
Traceback (most recent call last):
  File "/Users/.../.pyenv/versions/3.10.9/lib/python3.10/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
  File "/Users/.../.pyenv/versions/3.10.9/lib/python3.10/site-packages/discord/commands/core.py", line 980, in _invoke
    await self.callback(ctx, **kwargs)
  File "/Users/.../Documents/_DEVELOPER/discord/MidJourney-Wrapper/main.py", line 31, in mj_imagine
    await ctx.respond(
  File "/Users/.../.pyenv/versions/3.10.9/lib/python3.10/site-packages/discord/commands/context.py", line 282, in respond
    return await self.interaction.response.send_message(
  File "/Users/.../.pyenv/versions/3.10.9/lib/python3.10/site-packages/discord/interactions.py", line 825, in send_message
    await self._locked_response(
  File "/Users/.../.pyenv/versions/3.10.9/lib/python3.10/site-packages/discord/interactions.py", line 1090, in _locked_response
    await coro
  File "/Users/.../.pyenv/versions/3.10.9/lib/python3.10/site-packages/discord/webhook/async_.py", line 217, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/.../.pyenv/versions/3.10.9/lib/python3.10/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/Users/.../.pyenv/versions/3.10.9/lib/python3.10/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/Users/.../.pyenv/versions/3.10.9/lib/python3.10/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.
```

**Comment by torealise** [comment]
so is there a solution?
